name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
              with:
                  path: locker
            - uses: actions/checkout@v7
              with:
                  repository: braycarlson/nimble
                  path: nimble
            - uses: actions/checkout@v7
              with:
                  repository: braycarlson/wisp
                  path: wisp
            - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
              with:
                  version: 0.16.0
            - run: zig build ci --summary all
              working-directory: locker
